name: Build and push image

on:
  # push:
  #   branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
    steps:
      # - name: Dirs
      #   run: |
      #     mkdir -p /repo
      #     cd /repo
   
      # - name: apt update
      #   run: apt update

      # - name: install git
      #   run: apt install git -y

      - run: echo "Working with - ${{ gitea.repository }} - branch - ${{ gitea.ref }}"

      - name: Checkout repo 
        uses: actions/checkout@v4
              
      - name: Deploy
        run: |
          ls -la
          pwd
          docker buildx build -t ${{ vars.DOCKER_REGISTRY }}/synclias:latest .
          docker push ${{ vars.DOCKER_REGISTRY }}/synclias:latest
