"""Adding test field

Revision ID: 844881d98776
Revises: 
Create Date: 2025-11-10 17:29:37.176579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844881d98776'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_type2', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_records', schema=None) as batch_op:
        batch_op.drop_column('record_type2')

    # ### end Alembic commands ###
