"""Initial beta state

Revision ID: d82c2364e12f
Revises: 844881d98776
Create Date: 2025-11-10 17:30:14.274772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd82c2364e12f'
down_revision = '844881d98776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_records', schema=None) as batch_op:
        batch_op.drop_column('record_type2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_type2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
